version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn ChadChamberAPI.wsgi:application --bind 0.0.0.0:8000 --workers 4 --threads 4
    volumes:
      - .:/var/www/ChadChamberAPI
      - media_data:/var/www/ChadChamberAPI/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/var/www/ChadChamberAPI/static
      - media_data:/var/www/ChadChamberAPI/media
    ports:
      - "8002:80"
    depends_on:
      - web

volumes:
  postgres_data:
  media_data:
